[build]
builder = "DOCKERFILE"
dockerfilePath = "./apis/router/Dockerfile"
watchPatterns = [
    "apis/router/**",
    "packages/**",
    "!/*.md",
    "bun.lock",
    "package.json",
]

[deploy]
numReplicas = 1
healthcheckPath = "/route/health"
sleepApplication = true
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
region = "europe-west4"

[environments.pr.deploy]
sleepApplication = true

[environments.production-testnet.deploy]
sleepApplication = false
numReplicas = 3
